coincheck:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:
  minute_to_expire:
  trigger_price:

zaif:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:
  minute_to_expire:
  trigger_price:

bitflyer:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:
  minute_to_expire:
  trigger_price:

kraken:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:
  minute_to_expire:
  trigger_price:

difference: 
interval: 
slack_address:

initialize:


# 削除予定
amount:
scalping: