coincheck:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:

zaif:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:

bitflyer:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:

kraken:
  ACCESS_KEY:
  API_SECRET:
  amount:
  scalping:

difference: 
interval: 
slack_address:

initialize:


# 削除予定
amount:
scalping: