coincheck:
  ACCESS_KEY: 
  API_SECRET: 

zaif:
  ACCESS_KEY: 
  API_SECRET: 

bitflyer:
  ACCESS_KEY: 
  API_SECRET: 

kraken:
  ACCESS_KEY: 
  API_SECRET: 

amount:
difference: 
interval: 
slack_address:

initialize:
scalping: